### ISSUE TITLE
Sìn-bōng-ài ū siám tuā-siá--bô?

### ISSUE THREAD

**Issue by a8568730** [i3thuan5/KeSi#3]
PR #1 siá POJ tsuán-uānn leh tse būn-tê.
```
Ôa
Oâ
```

**Comment by sih4sing5hong5** [comment]
Mac sìn-bōng-ài phah--chhut-lâi--ê sī `ôa ÔA Ôa`

**Comment by a8568730** [comment]
Kiat-lūn: Bián siám tuā-siá.
